from uuid import UUID

import httpx

from evoapp_http.auth import IAM_Auth
from http_client_retries import with_retries_failed_requests
from http_client_retries import with_retries_if
from inference_activity.clients import IAM_HttpClient
from inference_activity.clients import ModelRunUsersApiClient
from inference_activity.clients import options
from inference_activity.clients.inference.call_model_run_client import CallModelApi
from inference_activity.models.inference.call_model_run_client.v1.requests import ModelItemMessage
from inference_activity.models.inference.call_model_run_client.v1.requests import (
    ModelTextToTextGenerationInputsRequestsOllama,
)
from inference_activity.models.inference.call_model_run_client.v1.responses import (
    ModelTextToTextGenerationResponseOllama,
)


def is_service_unavailable(response: httpx.Response) -> bool:
    return response.status_code in (
        httpx.codes.BAD_GATEWAY,  # 502
        httpx.codes.SERVICE_UNAVAILABLE,  # 503
        httpx.codes.GATEWAY_TIMEOUT,  # 504
    )


CP_CONSOLE_KEY_ID = "5516ef0c7e1fff59d5486fb51b9cd4fd"
CP_CONSOLE_SECRET = "54f0f0eb332ce599f2cc7901432c4442"
PROJECT_ID = "18f49bb5-127e-4949-ac49-eee30ba8f2cc"
# Создаем клиент в IAM для получения токена доступа
iam_client = IAM_HttpClient("https://iam.api.cloud.ru/")
URL_SUFFIX_MODEL_CALL_API_GW = "modelrun.inference.cloud.ru"

# Создаем и настраиваем Bff клиент в ModelRunUsersApiClient
inf_bff_client = ModelRunUsersApiClient(
    "https://console.cloud.ru",
    options.with_auth(
        IAM_Auth(
            key_id=CP_CONSOLE_KEY_ID,
            key_secret=CP_CONSOLE_SECRET,
            iam_client=iam_client,
        ),
    ),
    options.with_autogenerated_request_id(),
    options.with_autogenerated_traceparent(),
    with_retries_failed_requests(),
    with_retries_if(is_service_unavailable),
)

inf_api_gw_client = CallModelApi(
    URL_SUFFIX_MODEL_CALL_API_GW,
    # options.with_auth(
    #     IAM_Auth(
    #         key_id=CP_CONSOLE_KEY_ID,
    #         key_secret=CP_CONSOLE_SECRET,
    #         iam_client=iam_client,
    #     ),
    # ),  if you need auth
    options.with_autogenerated_request_id(),
    options.with_autogenerated_traceparent(),
    with_retries_failed_requests(),
)

if __name__ == "__main__":
    res = inf_bff_client.v1.get_list_model_run(project_id=UUID(PROJECT_ID))
    assert res.response.is_success
    print(res.model().model_dump_json(indent=2))
    request_payload = ModelTextToTextGenerationInputsRequestsOllama(
        model="tinyllama:latest",
        messages=[ModelItemMessage(role="user", content="why is the sky blue?")],
        keep_alive=1,
    )
    res_model_call = inf_api_gw_client.v1.call_model_run_with_compatible_openai(
        model_run_id=UUID("ad6f4f28-cba2-40a7-b7bf-0cf55cb4382c"),
        response_schema=ModelTextToTextGenerationResponseOllama,
        model_run_request_body_data=request_payload,
    )
    assert res.response.is_success
    print(res_model_call.model().model_dump_json(indent=2))