#!/usr/bin/env python3
"""Cloud.ru ML Inference CLI — manage model runs and call inference endpoints.

Usage:
    python ml_inference.py <command> [options]

Commands:
    catalog         List predefined models from Cloud.ru catalog
    catalog-detail  Show deployment configs for a predefined model
    deploy          Deploy a predefined model (recommended way to create)
    list            List all model runs
    get             Get model run details
    create          Create a custom model run (advanced)
    update          Update a model run
    delete          Delete a model run
    suspend         Suspend a model run
    resume          Resume a model run
    call            Call inference (OpenAI-compatible chat)
    embed           Call embedding endpoint
    rerank          Call rerank endpoint
    ping            Health check a model run
    history         Get model run event history
    quotas          Show project quota usage
    frameworks      List available framework/runtime versions

Environment variables required:
    CP_CONSOLE_KEY_ID   — Cloud.ru service account key ID
    CP_CONSOLE_SECRET   — Cloud.ru service account secret
    PROJECT_ID          — Cloud.ru project UUID
"""

import argparse
import json
import os
import sys
from uuid import UUID

import httpx
from evoapp_http.auth import IAM_Auth
from http_client_retries import with_retries_failed_requests, with_retries_if
from inference_activity.clients import IAM_HttpClient, ModelRunUsersApiClient, options
from inference_activity.clients.inference.call_model_run_client import CallModelApi
from inference_activity.enums import FrameworkTypeEnum, ModelTaskType, ResourcesTypeEnum
from inference_activity.models.inference.bff.v1.requests import (
    ConcurrencyType,
    KeepAliveDuration,
    ModelRegistry,
    ModelRunCreateItem,
    ModelScope,
    ModelSourceHuggingFace,
    ModelSourceOllama,
    OllamaOptions,
    Repository,
    Scaling,
    ScalingRulesConcurrencyType,
    VllmOptions,
)
from inference_activity.models.inference.call_model_run_client.v1.requests import (
    ModelEmbeddingInputRequestVllm,
    ModelGenerateInputRequestVllmSglang,
    ModelItemMessage,
    ModelRerankInputRequestVllm,
    ModelTextToTextGenerationInputsRequestsOllama,
)
from inference_activity.models.inference.call_model_run_client.v1.responses import (
    ModelEmbeddingResponseVllm,
    ModelGenerateResponseVllm,
    ModelRerankResponseVllm,
    ModelTextToTextGenerationResponseOllama,
)


def is_service_unavailable(response: httpx.Response) -> bool:
    return response.status_code in (502, 503, 504)


def get_env(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        print(f"Error: environment variable {name} is not set", file=sys.stderr)
        sys.exit(1)
    return val


def build_clients():
    key_id = get_env("CP_CONSOLE_KEY_ID")
    key_secret = get_env("CP_CONSOLE_SECRET")
    project_id = UUID(get_env("PROJECT_ID"))

    iam_client = IAM_HttpClient("https://iam.api.cloud.ru/")
    auth = IAM_Auth(key_id=key_id, key_secret=key_secret, iam_client=iam_client)

    bff_client = ModelRunUsersApiClient(
        "https://console.cloud.ru",
        options.with_auth(auth),
        options.with_autogenerated_request_id(),
        options.with_autogenerated_traceparent(),
        with_retries_failed_requests(),
    )

    call_client = CallModelApi(
        "modelrun.inference.cloud.ru",
        options.with_autogenerated_request_id(),
        options.with_autogenerated_traceparent(),
        with_retries_failed_requests(),
    )

    call_client_with_auth = CallModelApi(
        "modelrun.inference.cloud.ru",
        options.with_auth(auth),
        options.with_autogenerated_request_id(),
        options.with_autogenerated_traceparent(),
        with_retries_failed_requests(),
    )

    return bff_client, call_client, call_client_with_auth, project_id


def print_json(obj):
    if hasattr(obj, "model_dump_json"):
        print(obj.model_dump_json(indent=2))
    elif hasattr(obj, "model_dump"):
        print(json.dumps(obj.model_dump(), indent=2, default=str))
    else:
        print(json.dumps(obj, indent=2, default=str))


def check_response(res, action: str):
    if not res.response.is_success:
        print(
            f"Error {action}: HTTP {res.response.status_code}",
            file=sys.stderr,
        )
        print(res.response.text, file=sys.stderr)
        sys.exit(1)


# --- Commands ---


def cmd_list(args):
    bff, _, _, project_id = build_clients()
    params = {"limit": args.limit or 100, "offset": args.offset or 0}
    res = bff.v1.get_list_model_run(project_id=project_id, params=params)
    check_response(res, "listing model runs")
    data = res.model()
    print(f"Total: {data.total}")
    for mr in data.model_runs:
        print(
            f"  {mr.model_run_id} | {mr.name} | {mr.status} | "
            f"{mr.framework_type} | {mr.resource_type} | gpu={mr.gpu_count}"
        )


def cmd_get(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_details_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "getting model run details")
    print_json(res.model().model_run)


def cmd_create(args):
    """Create a model run using raw JSON payload.

    The Cloud.ru API is strict about null values and requires specific field
    formats, so we build the payload as a dict and POST it directly via httpx
    instead of relying on SDK model serialization.
    """
    bff, _, _, project_id = build_clients()

    framework_enum_map = {
        "VLLM": "FrameworkType_VLLM",
        "SGLANG": "FrameworkType_SGLANG",
        "OLLAMA": "FrameworkType_OLLAMA",
        "TRANSFORMERS": "FrameworkType_TRANSFORMERS",
        "DIFFUSERS": "FrameworkType_DIFFUSERS",
        "COMFY": "FrameworkType_COMFY_UI",
    }
    resource_enum_map = {
        "GPU_A100": "ResourceType_GPU_A100_NVLINK",
        "GPU_H100": "ResourceType_GPU_H100",
        "GPU_V100": "ResourceType_GPU_V100",
        "CPU": "ResourceType_CPU",
    }
    task_enum_map = {t.name: t.value for t in ModelTaskType}

    fw = args.framework.upper()
    framework_val = framework_enum_map.get(fw)
    if not framework_val:
        print(f"Unknown framework: {args.framework}", file=sys.stderr)
        sys.exit(1)

    resource_val = resource_enum_map.get(args.resource.upper()) if args.resource else "ResourceType_GPU_A100_NVLINK"
    task_val = task_enum_map.get(args.task.upper()) if args.task else "ModelTaskType_GENERATE"

    # Build model source
    repo = args.repo or ""
    model_name = args.model_name
    if not model_name and "/" in repo:
        repo, model_name = repo.split("/", 1)

    if args.source_type == "huggingface":
        model_source = {
            "huggingFaceRepository": {
                "repo": repo,
                "model": model_name or "",
                "revision": args.revision or "main",
                "filePaths": [],
            },
            "secret": "",
            "repoSize": 0,
        }
    elif args.source_type == "ollama":
        model_source = {
            "ollama": {
                "model": model_name or repo,
                "repo": "",
                "revision": "",
            },
            "secret": "",
            "repoSize": 0,
        }
    elif args.source_type == "registry":
        model_source = {
            "modelRegistry": {
                "repo": repo,
                "model": model_name or "",
                "revision": args.revision or "",
            },
            "secret": "",
            "repoSize": 0,
        }
    elif args.source_type == "modelscope":
        model_source = {
            "modelScope": {
                "repo": repo,
                "model": model_name or "",
                "revision": args.revision or "",
            },
            "secret": "",
            "repoSize": 0,
        }
    else:
        model_source = {}

    # Build serving options — use dynamicalOptions for VLLM/SGLANG
    serving_options = {}
    if fw in ("VLLM", "SGLANG"):
        dyn_args = args.vllm_args if hasattr(args, "vllm_args") and args.vllm_args else []
        serving_options = {
            "dynamicalOptions": {
                "args": dyn_args,
                "loraModules": [],
            }
        }
    elif fw == "OLLAMA":
        serving_options = {"ollamaOptions": {}}
    elif fw == "TRANSFORMERS":
        serving_options = {"transformersOptions": {}}
    elif fw == "DIFFUSERS":
        serving_options = {"diffusersOptions": {}}

    # Build scaling (required)
    min_scale = args.min_scale if args.min_scale is not None else 1
    max_scale = args.max_scale if args.max_scale is not None else 1
    scaling = {
        "minScale": min_scale,
        "maxScale": max_scale,
        "scalingRules": {"rpsType": {"value": 200}},
    }

    # Resolve runtime template if not provided
    runtime_template_id = args.runtime_template_id
    if not runtime_template_id:
        # Auto-pick latest active runtime for the framework
        rt_res = bff.v1.get_framework_versions(
            project_id=project_id, params={"limit": 100, "offset": 0}
        )
        if rt_res.response.is_success:
            for rt in rt_res.model().runtime_templates:
                if rt.framework_type == framework_enum_map.get(fw) and rt.is_active:
                    runtime_template_id = rt.id
                    break
        if not runtime_template_id:
            print("Error: could not auto-detect runtime template. Pass --runtime-template-id.", file=sys.stderr)
            sys.exit(1)

    payload = {
        "name": args.name,
        "frameworkType": framework_val,
        "resourceType": resource_val,
        "gpuCount": args.gpu_count or 1,
        "gpuGbMemory": args.gpu_memory or 20,
        "modelTaskType": task_val,
        "runtimeTemplateId": runtime_template_id,
        "modelSource": model_source,
        "servingOptions": serving_options,
        "scaling": scaling,
        "options": {
            "isEnabledAuth": False,
            "isEnabledLogging": False,
        },
    }

    # POST directly via the underlying httpx client to avoid null serialization issues
    import httpx as _httpx

    response = bff.post(
        f"u-api/inference/model-run/v1/{project_id}/modelruns",
        json=payload,
    )
    if not response.is_success:
        print(f"Error creating model run: HTTP {response.status_code}", file=sys.stderr)
        print(response.text, file=sys.stderr)
        sys.exit(1)
    data = response.json()
    print(f"Created model run: {data.get('modelRunId', data)}")


def cmd_catalog(args):
    """List predefined models from the Cloud.ru catalog."""
    bff, _, _, _ = build_clients()
    params = {
        "limit": args.limit or 100,
        "offset": args.offset or 0,
    }
    if args.query:
        params["query"] = args.query
    if args.sort:
        params["sort"] = args.sort

    response = bff.get(
        "u-api/inference/model-run/v1/predefined-models",
        params=params,
    )
    if not response.is_success:
        print(f"Error: HTTP {response.status_code}", file=sys.stderr)
        print(response.text, file=sys.stderr)
        sys.exit(1)

    data = response.json()
    total = data.get("total", 0)
    has_more = data.get("hasMore", False)
    cards = data.get("modelCards", [])
    print(f"Predefined models ({len(cards)} shown, {total} total, hasMore={has_more}):\n")
    for c in cards:
        tags = ", ".join(c.get("tags", []))
        tags_str = f" [{tags}]" if tags else ""
        print(
            f"  {c['id']} | {c['name']:<40} | {c.get('vendorName',''):<10} "
            f"| {c.get('paramsBn','')}B | ctx={c.get('contextK','')}K "
            f"| {c.get('price','')} rub/hour{tags_str}"
        )


def cmd_catalog_detail(args):
    """Show detailed configs for a predefined model."""
    bff, _, _, _ = build_clients()
    response = bff.get(
        f"u-api/inference/model-run/v1/predefined-models/{args.model_card_id}",
    )
    if not response.is_success:
        print(f"Error: HTTP {response.status_code}", file=sys.stderr)
        print(response.text, file=sys.stderr)
        sys.exit(1)

    data = response.json()
    card = data.get("modelCard", {})
    configs = data.get("modelCardConfigs", [])

    print(f"Model: {card.get('name', '?')}")
    print(f"Vendor: {card.get('vendorName', '?')}")
    print(f"Task: {card.get('taskType', '?')}")
    print(f"Params: {card.get('paramsBn', '?')}B | Context: {card.get('contextK', '?')}K")
    print(f"License: {card.get('licenseName', '?')}")
    print(f"Description: {card.get('description', '')[:200]}")
    print(f"\nAvailable configurations ({len(configs)}):")
    for i, cfg in enumerate(configs):
        print(
            f"\n  [{i}] GPU: {cfg.get('allowedGpu', '?')} x{cfg.get('gpuCount', '?')} "
            f"({cfg.get('gpuMemoryAllocGb', '?')}GB) | "
            f"Framework: {cfg.get('frameworkType', '?')} {cfg.get('frameworkVersion', '')} | "
            f"Price: {cfg.get('price', '?')} rub/day"
        )
        print(f"      Config ID: {cfg.get('id', '?')}")
        print(f"      Runtime: {cfg.get('runtimeTemplateId', '?')}")


def cmd_deploy(args):
    """Deploy a predefined model — fetches exact config from catalog and creates model run."""
    bff, _, _, project_id = build_clients()

    # 1. Fetch model card details
    response = bff.get(
        f"u-api/inference/model-run/v1/predefined-models/{args.model_card_id}",
    )
    if not response.is_success:
        print(f"Error fetching model card: HTTP {response.status_code}", file=sys.stderr)
        print(response.text, file=sys.stderr)
        sys.exit(1)

    data = response.json()
    card = data.get("modelCard", {})
    configs = data.get("modelCardConfigs", [])

    if not configs:
        print("Error: no configurations available for this model", file=sys.stderr)
        sys.exit(1)

    # 2. Pick config (by index or auto-pick first)
    config_index = args.config_index if args.config_index is not None else 0
    if config_index >= len(configs):
        print(f"Error: config index {config_index} out of range (0-{len(configs)-1})", file=sys.stderr)
        sys.exit(1)
    cfg = configs[config_index]

    model_name = args.name or card.get("name", "model-run")
    task_type = card.get("taskType", "ModelTaskType_GENERATE")

    # 3. Build payload from the predefined config — no guessing
    payload = {
        "name": model_name,
        "frameworkType": cfg["frameworkType"],
        "resourceType": cfg["allowedGpu"],
        "gpuCount": cfg["gpuCount"],
        "gpuGbMemory": cfg["gpuMemoryAllocGb"],
        "modelTaskType": task_type,
        "runtimeTemplateId": cfg["runtimeTemplateId"],
        "modelSource": card.get("modelSource", {}),
        "servingOptions": cfg.get("servingOptions", {}),
        "scaling": cfg.get("scaling", {"minScale": 1, "maxScale": 1, "scalingRules": {"rpsType": {"value": 200}}}),
        "options": {
            "isEnabledAuth": False,
            "isEnabledLogging": False,
        },
    }

    print(f"Deploying '{card.get('name', '?')}' with config [{config_index}]:")
    print(f"  GPU: {cfg.get('allowedGpu')} x{cfg.get('gpuCount')} ({cfg.get('gpuMemoryAllocGb')}GB)")
    print(f"  Framework: {cfg.get('frameworkType')} {cfg.get('frameworkVersion', '')}")
    print(f"  Price: {cfg.get('price', '?')} rub/day")

    # 4. Create model run
    create_resp = bff.post(
        f"u-api/inference/model-run/v1/{project_id}/modelruns",
        json=payload,
    )
    if not create_resp.is_success:
        print(f"\nError creating model run: HTTP {create_resp.status_code}", file=sys.stderr)
        print(create_resp.text, file=sys.stderr)
        sys.exit(1)

    result = create_resp.json()
    model_run_id = result.get("modelRunId", result)
    print(f"\nCreated model run: {model_run_id}")
    print(f"Public URL: {model_run_id}.modelrun.inference.cloud.ru")


def cmd_update(args):
    bff, _, _, project_id = build_clients()

    update_fields = {}
    if args.name:
        update_fields["name"] = args.name
    if args.min_scale is not None or args.max_scale is not None:
        update_fields["scaling"] = Scaling(
            min_scale=args.min_scale or 0,
            max_scale=args.max_scale or 1,
            scaling_rules=ScalingRulesConcurrencyType(
                concurrency_type=ConcurrencyType(soft=1, hard=2),
            ),
            keep_alive_duration=KeepAliveDuration(
                hours=0, minutes=args.keep_alive_minutes or 15, seconds=0
            ),
        )

    body = ModelRunCreateItem(**update_fields)
    res = bff.v1.update_model_run(
        project_id=project_id,
        model_run_id=UUID(args.model_run_id),
        model_run_body_data=body,
    )
    check_response(res, "updating model run")
    print("Updated successfully")


def cmd_delete(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.delete_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "deleting model run")
    print("Deleted successfully")


def cmd_suspend(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.suspend_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "suspending model run")
    print("Suspended successfully")


def cmd_resume(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.resume_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "resuming model run")
    print("Resumed successfully")


def cmd_call(args):
    _, call_client, call_client_auth, project_id = build_clients()
    client = call_client_auth if args.with_auth else call_client
    model_run_id = UUID(args.model_run_id)

    messages = [ModelItemMessage(role="user", content=args.prompt)]
    if args.system:
        messages.insert(0, ModelItemMessage(role="system", content=args.system))

    if args.framework and args.framework.upper() in ("VLLM", "SGLANG"):
        payload = ModelGenerateInputRequestVllmSglang(
            model=args.model_name or "",
            messages=messages,
            temperature=args.temperature,
            top_p=args.top_p,
        )
        response_schema = ModelGenerateResponseVllm
    else:
        payload = ModelTextToTextGenerationInputsRequestsOllama(
            model=args.model_name or "",
            messages=messages,
            keep_alive=1,
        )
        response_schema = ModelTextToTextGenerationResponseOllama

    res = client.v1.call_model_run_with_compatible_openai(
        model_run_id=model_run_id,
        response_schema=response_schema,
        model_run_request_body_data=payload,
    )
    check_response(res, "calling model")
    result = res.model()
    if result.choices:
        print(result.choices[0].message.content)
    print(f"\nTokens: {result.usage.total_tokens}")


def cmd_embed(args):
    _, call_client, call_client_auth, project_id = build_clients()
    client = call_client_auth if args.with_auth else call_client

    payload = ModelEmbeddingInputRequestVllm(
        model=args.model_name or "",
        input=args.texts,
    )

    res = client.v1.call_embedding_model_run_with_compatible_openai(
        model_run_id=UUID(args.model_run_id),
        response_schema=ModelEmbeddingResponseVllm,
        model_run_request_body_data=payload,
    )
    check_response(res, "calling embeddings")
    result = res.model()
    for item in result.data:
        print(f"[{item.index}] dim={len(item.embedding)} first_3={item.embedding[:3]}")
    print(f"\nTokens: {result.usage.total_tokens}")


def cmd_rerank(args):
    _, call_client, call_client_auth, project_id = build_clients()
    client = call_client_auth if args.with_auth else call_client

    payload = ModelRerankInputRequestVllm(
        model=args.model_name or "",
        query=args.query,
        documents=args.documents,
    )

    res = client.v1.call_rerank_model_run_with_compatible_openai(
        model_run_id=UUID(args.model_run_id),
        response_schema=ModelRerankResponseVllm,
        model_run_request_body_data=payload,
    )
    check_response(res, "calling rerank")
    for r in res.model().results:
        print(f"[{r.index}] score={r.relevance_score:.4f} | {r.document.text[:80]}")


def cmd_ping(args):
    _, call_client, call_client_auth, _ = build_clients()
    client = call_client_auth if args.with_auth else call_client
    res = client.v1.ping_model_run_with_compatible_openai(
        model_run_id=UUID(args.model_run_id),
    )
    if res.response.is_success:
        print(f"Model run {args.model_run_id} is healthy")
    else:
        print(
            f"Model run {args.model_run_id} is NOT healthy "
            f"(HTTP {res.response.status_code})"
        )
        sys.exit(1)


def cmd_history(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_history_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "getting history")
    for event in res.model().events:
        print(f"  {event.event_type} at {event.version} by {event.author_id}")


def cmd_quotas(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_quota_usage(project_id=project_id)
    check_response(res, "getting quotas")
    data = res.response.json()
    for q in data.get("data", []):
        print(f"  {q['resourceType']}: {q['free']} free / {q['limit']} total")


def cmd_frameworks(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_framework_versions(project_id=project_id, params={"limit": 100, "offset": 0})
    check_response(res, "getting frameworks")
    for rt in res.model().runtime_templates:
        gpus = ", ".join(
            f"{g.resource_type}{'(default)' if g.is_default else ''}"
            for g in rt.gpus
            if g.is_allowed
        )
        active = "active" if rt.is_active else "inactive"
        print(f"  {rt.framework_type} v{rt.version} [{active}] (id={rt.id}) GPUs: [{gpus}]")


def main():
    parser = argparse.ArgumentParser(
        description="Cloud.ru ML Inference CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list
    p_list = subparsers.add_parser("list", help="List model runs")
    p_list.add_argument("--limit", type=int, help="Max results")
    p_list.add_argument("--offset", type=int, help="Offset for pagination")

    # get
    p_get = subparsers.add_parser("get", help="Get model run details")
    p_get.add_argument("model_run_id", help="Model run UUID")

    # create
    p_create = subparsers.add_parser("create", help="Create a model run")
    p_create.add_argument("--name", required=True, help="Model run name")
    p_create.add_argument(
        "--framework",
        required=True,
        choices=["VLLM", "SGLANG", "OLLAMA", "TRANSFORMERS", "DIFFUSERS", "COMFY"],
        help="Framework type",
    )
    p_create.add_argument(
        "--resource",
        choices=["GPU_A100", "GPU_H100", "GPU_V100", "CPU"],
        help="Resource type",
    )
    p_create.add_argument(
        "--task",
        help="Task type (e.g. TEXT_2_TEXT_GENERATION, EMBEDDING, TEXT_2_IMAGE_GENERATION)",
    )
    p_create.add_argument(
        "--source-type",
        choices=["huggingface", "ollama", "registry", "modelscope"],
        default="huggingface",
        help="Model source type",
    )
    p_create.add_argument("--repo", help="Repository path (e.g. org/model)")
    p_create.add_argument("--model-name", help="Model name within source")
    p_create.add_argument("--revision", help="Model revision/tag")
    p_create.add_argument("--gpu-count", type=int, help="Number of GPUs")
    p_create.add_argument("--gpu-memory", type=int, help="GPU memory in GB")
    p_create.add_argument("--runtime-template-id", help="Runtime template ID (auto-detected if omitted)")
    p_create.add_argument("--min-scale", type=int, help="Min scale (default: 1)")
    p_create.add_argument("--max-scale", type=int, help="Max scale (default: 1)")
    p_create.add_argument(
        "--vllm-args",
        type=json.loads,
        help='JSON array of dynamical args, e.g. \'[{"key":"dtype","value":"bfloat16","parameterType":"PARAMETER_TYPE_ARG_KV_QUOTED"}]\'',
    )

    # update
    p_update = subparsers.add_parser("update", help="Update a model run")
    p_update.add_argument("model_run_id", help="Model run UUID")
    p_update.add_argument("--name", help="New name")
    p_update.add_argument("--min-scale", type=int, help="New min scale")
    p_update.add_argument("--max-scale", type=int, help="New max scale")
    p_update.add_argument("--keep-alive-minutes", type=int, help="Keep alive minutes")

    # delete
    p_del = subparsers.add_parser("delete", help="Delete a model run")
    p_del.add_argument("model_run_id", help="Model run UUID")

    # suspend
    p_sus = subparsers.add_parser("suspend", help="Suspend a model run")
    p_sus.add_argument("model_run_id", help="Model run UUID")

    # resume
    p_res = subparsers.add_parser("resume", help="Resume a model run")
    p_res.add_argument("model_run_id", help="Model run UUID")

    # call
    p_call = subparsers.add_parser("call", help="Call model inference (chat)")
    p_call.add_argument("model_run_id", help="Model run UUID")
    p_call.add_argument("--prompt", required=True, help="User message")
    p_call.add_argument("--system", help="System message")
    p_call.add_argument("--model-name", help="Model name for the request")
    p_call.add_argument(
        "--framework", choices=["VLLM", "SGLANG", "OLLAMA"], help="Framework hint"
    )
    p_call.add_argument("--temperature", type=float, default=0.7)
    p_call.add_argument("--top-p", type=float, default=0.9)
    p_call.add_argument("--with-auth", action="store_true", help="Use IAM auth for call")

    # embed
    p_embed = subparsers.add_parser("embed", help="Call embedding endpoint")
    p_embed.add_argument("model_run_id", help="Model run UUID")
    p_embed.add_argument("--texts", nargs="+", required=True, help="Texts to embed")
    p_embed.add_argument("--model-name", help="Model name")
    p_embed.add_argument("--with-auth", action="store_true")

    # rerank
    p_rerank = subparsers.add_parser("rerank", help="Call rerank endpoint")
    p_rerank.add_argument("model_run_id", help="Model run UUID")
    p_rerank.add_argument("--query", required=True, help="Query string")
    p_rerank.add_argument("--documents", nargs="+", required=True, help="Documents")
    p_rerank.add_argument("--model-name", help="Model name")
    p_rerank.add_argument("--with-auth", action="store_true")

    # ping
    p_ping = subparsers.add_parser("ping", help="Health check a model run")
    p_ping.add_argument("model_run_id", help="Model run UUID")
    p_ping.add_argument("--with-auth", action="store_true")

    # history
    p_hist = subparsers.add_parser("history", help="Get model run event history")
    p_hist.add_argument("model_run_id", help="Model run UUID")

    # quotas
    subparsers.add_parser("quotas", help="Show project quota usage")

    # frameworks
    subparsers.add_parser("frameworks", help="List available frameworks/runtimes")

    # catalog
    p_catalog = subparsers.add_parser("catalog", help="List predefined models from Cloud.ru catalog")
    p_catalog.add_argument("--query", help="Search query")
    p_catalog.add_argument("--limit", type=int, help="Max results (default: 100)")
    p_catalog.add_argument("--offset", type=int, help="Offset for pagination")
    p_catalog.add_argument(
        "--sort", default="SORT_TYPE_PRICE_ASC",
        help="Sort order (SORT_TYPE_PRICE_ASC, SORT_TYPE_PRICE_DESC, etc.)",
    )

    # catalog-detail
    p_cat_detail = subparsers.add_parser("catalog-detail", help="Show configs for a predefined model")
    p_cat_detail.add_argument("model_card_id", help="Model card UUID from catalog")

    # deploy
    p_deploy = subparsers.add_parser("deploy", help="Deploy a predefined model (recommended)")
    p_deploy.add_argument("model_card_id", help="Model card UUID from catalog")
    p_deploy.add_argument("--name", help="Custom name (default: model name from catalog)")
    p_deploy.add_argument("--config-index", type=int, help="Config index if multiple available (default: 0)")

    args = parser.parse_args()

    commands = {
        "list": cmd_list,
        "get": cmd_get,
        "create": cmd_create,
        "update": cmd_update,
        "delete": cmd_delete,
        "suspend": cmd_suspend,
        "resume": cmd_resume,
        "call": cmd_call,
        "embed": cmd_embed,
        "rerank": cmd_rerank,
        "ping": cmd_ping,
        "history": cmd_history,
        "quotas": cmd_quotas,
        "frameworks": cmd_frameworks,
        "catalog": cmd_catalog,
        "catalog-detail": cmd_catalog_detail,
        "deploy": cmd_deploy,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
