#!/usr/bin/env python3
"""Cloud.ru ML Inference CLI — manage model runs and call inference endpoints.

Usage:
    python ml_inference.py <command> [options]

Commands:
    list        List all model runs
    get         Get model run details
    create      Create a new model run
    update      Update a model run
    delete      Delete a model run
    suspend     Suspend a model run
    resume      Resume a model run
    call        Call inference (OpenAI-compatible chat)
    embed       Call embedding endpoint
    rerank      Call rerank endpoint
    ping        Health check a model run
    history     Get model run event history
    quotas      Show project quota usage
    frameworks  List available framework/runtime versions

Environment variables required:
    CP_CONSOLE_KEY_ID   — Cloud.ru service account key ID
    CP_CONSOLE_SECRET   — Cloud.ru service account secret
    PROJECT_ID          — Cloud.ru project UUID
"""

import argparse
import json
import os
import sys
from uuid import UUID

import httpx
from evoapp_http.auth import IAM_Auth
from http_client_retries import with_retries_failed_requests, with_retries_if
from inference_activity.clients import IAM_HttpClient, ModelRunUsersApiClient, options
from inference_activity.clients.inference.call_model_run_client import CallModelApi
from inference_activity.enums import FrameworkTypeEnum, ModelTaskType, ResourcesTypeEnum
from inference_activity.models.inference.bff.v1.requests import (
    ConcurrencyType,
    KeepAliveDuration,
    ModelRegistry,
    ModelRunCreateItem,
    ModelScope,
    ModelSourceHuggingFace,
    ModelSourceOllama,
    OllamaOptions,
    Repository,
    Scaling,
    ScalingRulesConcurrencyType,
    VllmOptions,
)
from inference_activity.models.inference.call_model_run_client.v1.requests import (
    ModelEmbeddingInputRequestVllm,
    ModelGenerateInputRequestVllmSglang,
    ModelItemMessage,
    ModelRerankInputRequestVllm,
    ModelTextToTextGenerationInputsRequestsOllama,
)
from inference_activity.models.inference.call_model_run_client.v1.responses import (
    ModelEmbeddingResponseVllm,
    ModelGenerateResponseVllm,
    ModelRerankResponseVllm,
    ModelTextToTextGenerationResponseOllama,
)


def is_service_unavailable(response: httpx.Response) -> bool:
    return response.status_code in (502, 503, 504)


def get_env(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        print(f"Error: environment variable {name} is not set", file=sys.stderr)
        sys.exit(1)
    return val


def build_clients():
    key_id = get_env("CP_CONSOLE_KEY_ID")
    key_secret = get_env("CP_CONSOLE_SECRET")
    project_id = UUID(get_env("PROJECT_ID"))

    iam_client = IAM_HttpClient("https://iam.api.cloud.ru/")
    auth = IAM_Auth(key_id=key_id, key_secret=key_secret, iam_client=iam_client)

    bff_client = ModelRunUsersApiClient(
        "https://console.cloud.ru",
        options.with_auth(auth),
        options.with_autogenerated_request_id(),
        options.with_autogenerated_traceparent(),
        with_retries_failed_requests(),
        with_retries_if(is_service_unavailable),
    )

    call_client = CallModelApi(
        "modelrun.inference.cloud.ru",
        options.with_autogenerated_request_id(),
        options.with_autogenerated_traceparent(),
        with_retries_failed_requests(),
    )

    call_client_with_auth = CallModelApi(
        "modelrun.inference.cloud.ru",
        options.with_auth(auth),
        options.with_autogenerated_request_id(),
        options.with_autogenerated_traceparent(),
        with_retries_failed_requests(),
    )

    return bff_client, call_client, call_client_with_auth, project_id


def print_json(obj):
    if hasattr(obj, "model_dump_json"):
        print(obj.model_dump_json(indent=2))
    elif hasattr(obj, "model_dump"):
        print(json.dumps(obj.model_dump(), indent=2, default=str))
    else:
        print(json.dumps(obj, indent=2, default=str))


def check_response(res, action: str):
    if not res.response.is_success:
        print(
            f"Error {action}: HTTP {res.response.status_code}",
            file=sys.stderr,
        )
        print(res.response.text, file=sys.stderr)
        sys.exit(1)


# --- Commands ---


def cmd_list(args):
    bff, _, _, project_id = build_clients()
    params = {}
    if args.limit:
        params["limit"] = args.limit
    if args.offset:
        params["offset"] = args.offset
    res = bff.v1.get_list_model_run(project_id=project_id, params=params or None)
    check_response(res, "listing model runs")
    data = res.model()
    print(f"Total: {data.total}")
    for mr in data.model_runs:
        print(
            f"  {mr.model_run_id} | {mr.name} | {mr.status} | "
            f"{mr.framework_type} | {mr.resource_type} | gpu={mr.gpu_count}"
        )


def cmd_get(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_details_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "getting model run details")
    print_json(res.model().model_run)


def cmd_create(args):
    bff, _, _, project_id = build_clients()

    framework_map = {
        "VLLM": FrameworkTypeEnum.VLLM,
        "SGLANG": FrameworkTypeEnum.SGLANG,
        "OLLAMA": FrameworkTypeEnum.OLLAMA,
        "TRANSFORMERS": FrameworkTypeEnum.TRANSFORMERS,
        "DIFFUSERS": FrameworkTypeEnum.DIFFUSERS,
        "COMFY": FrameworkTypeEnum.COMFY,
    }
    resource_map = {
        "GPU_A100": ResourcesTypeEnum.GPU_A100,
        "GPU_H100": ResourcesTypeEnum.GPU_H100,
        "GPU_V100": ResourcesTypeEnum.GPU_V100,
        "CPU": ResourcesTypeEnum.CPU,
    }
    task_map = {t.name: t for t in ModelTaskType}

    framework = framework_map.get(args.framework.upper())
    if not framework:
        print(f"Unknown framework: {args.framework}", file=sys.stderr)
        sys.exit(1)

    resource = resource_map.get(args.resource.upper()) if args.resource else None
    task = task_map.get(args.task.upper()) if args.task else None

    # Build model source
    model_source = None
    if args.source_type == "huggingface":
        model_source = ModelSourceHuggingFace(
            hugging_face_repository=Repository(
                repo=args.repo,
                model=args.model_name,
                revision=args.revision,
            ),
        )
    elif args.source_type == "ollama":
        model_source = ModelSourceOllama(
            ollama=Repository(model=args.model_name or args.repo),
        )
    elif args.source_type == "registry":
        model_source = ModelRegistry(
            model_registry=Repository(repo=args.repo, model=args.model_name),
        )
    elif args.source_type == "modelscope":
        model_source = ModelScope(
            model_scope=Repository(repo=args.repo, revision=args.revision),
        )

    # Build scaling
    scaling = None
    if args.min_scale is not None or args.max_scale is not None:
        scaling = Scaling(
            min_scale=args.min_scale or 0,
            max_scale=args.max_scale or 1,
            scaling_rules=ScalingRulesConcurrencyType(
                concurrency_type=ConcurrencyType(soft=1, hard=2),
            ),
            keep_alive_duration=KeepAliveDuration(
                hours=0, minutes=args.keep_alive_minutes or 15, seconds=0
            ),
        )

    body = ModelRunCreateItem(
        name=args.name,
        framework_type=framework,
        resource_type=resource,
        model_task_type=task,
        model_source=model_source,
        gpu_count=args.gpu_count,
        gpu_gb_memory=args.gpu_memory,
        runtime_template_id=args.runtime_template_id,
        scaling=scaling,
    )

    res = bff.v1.create_model_run(project_id=project_id, model_run_body_data=body)
    check_response(res, "creating model run")
    print(f"Created model run: {res.model().model_run_id}")


def cmd_update(args):
    bff, _, _, project_id = build_clients()

    update_fields = {}
    if args.name:
        update_fields["name"] = args.name
    if args.min_scale is not None or args.max_scale is not None:
        update_fields["scaling"] = Scaling(
            min_scale=args.min_scale or 0,
            max_scale=args.max_scale or 1,
            scaling_rules=ScalingRulesConcurrencyType(
                concurrency_type=ConcurrencyType(soft=1, hard=2),
            ),
            keep_alive_duration=KeepAliveDuration(
                hours=0, minutes=args.keep_alive_minutes or 15, seconds=0
            ),
        )

    body = ModelRunCreateItem(**update_fields)
    res = bff.v1.update_model_run(
        project_id=project_id,
        model_run_id=UUID(args.model_run_id),
        model_run_body_data=body,
    )
    check_response(res, "updating model run")
    print("Updated successfully")


def cmd_delete(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.delete_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "deleting model run")
    print("Deleted successfully")


def cmd_suspend(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.suspend_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "suspending model run")
    print("Suspended successfully")


def cmd_resume(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.resume_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "resuming model run")
    print("Resumed successfully")


def cmd_call(args):
    _, call_client, call_client_auth, project_id = build_clients()
    client = call_client_auth if args.with_auth else call_client
    model_run_id = UUID(args.model_run_id)

    messages = [ModelItemMessage(role="user", content=args.prompt)]
    if args.system:
        messages.insert(0, ModelItemMessage(role="system", content=args.system))

    if args.framework and args.framework.upper() in ("VLLM", "SGLANG"):
        payload = ModelGenerateInputRequestVllmSglang(
            model=args.model_name or "",
            messages=messages,
            temperature=args.temperature,
            top_p=args.top_p,
        )
        response_schema = ModelGenerateResponseVllm
    else:
        payload = ModelTextToTextGenerationInputsRequestsOllama(
            model=args.model_name or "",
            messages=messages,
            keep_alive=1,
        )
        response_schema = ModelTextToTextGenerationResponseOllama

    res = client.v1.call_model_run_with_compatible_openai(
        model_run_id=model_run_id,
        response_schema=response_schema,
        model_run_request_body_data=payload,
    )
    check_response(res, "calling model")
    result = res.model()
    if result.choices:
        print(result.choices[0].message.content)
    print(f"\nTokens: {result.usage.total_tokens}")


def cmd_embed(args):
    _, call_client, call_client_auth, project_id = build_clients()
    client = call_client_auth if args.with_auth else call_client

    payload = ModelEmbeddingInputRequestVllm(
        model=args.model_name or "",
        input=args.texts,
    )

    res = client.v1.call_embedding_model_run_with_compatible_openai(
        model_run_id=UUID(args.model_run_id),
        response_schema=ModelEmbeddingResponseVllm,
        model_run_request_body_data=payload,
    )
    check_response(res, "calling embeddings")
    result = res.model()
    for item in result.data:
        print(f"[{item.index}] dim={len(item.embedding)} first_3={item.embedding[:3]}")
    print(f"\nTokens: {result.usage.total_tokens}")


def cmd_rerank(args):
    _, call_client, call_client_auth, project_id = build_clients()
    client = call_client_auth if args.with_auth else call_client

    payload = ModelRerankInputRequestVllm(
        model=args.model_name or "",
        query=args.query,
        documents=args.documents,
    )

    res = client.v1.call_rerank_model_run_with_compatible_openai(
        model_run_id=UUID(args.model_run_id),
        response_schema=ModelRerankResponseVllm,
        model_run_request_body_data=payload,
    )
    check_response(res, "calling rerank")
    for r in res.model().results:
        print(f"[{r.index}] score={r.relevance_score:.4f} | {r.document.text[:80]}")


def cmd_ping(args):
    _, call_client, call_client_auth, _ = build_clients()
    client = call_client_auth if args.with_auth else call_client
    res = client.v1.ping_model_run_with_compatible_openai(
        model_run_id=UUID(args.model_run_id),
    )
    if res.response.is_success:
        print(f"Model run {args.model_run_id} is healthy")
    else:
        print(
            f"Model run {args.model_run_id} is NOT healthy "
            f"(HTTP {res.response.status_code})"
        )
        sys.exit(1)


def cmd_history(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_history_model_run(
        project_id=project_id, model_run_id=UUID(args.model_run_id)
    )
    check_response(res, "getting history")
    for event in res.model().events:
        print(f"  {event.event_type} at {event.version} by {event.author_id}")


def cmd_quotas(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_quota_usage(project_id=project_id)
    check_response(res, "getting quotas")
    for q in res.model().data:
        print(f"  {q.resource_type}: {q.free} free / {q.limit} total")


def cmd_frameworks(args):
    bff, _, _, project_id = build_clients()
    res = bff.v1.get_framework_versions(project_id=project_id, params={})
    check_response(res, "getting frameworks")
    for rt in res.model().runtime_templates:
        gpus = ", ".join(
            f"{g.resource_type}{'(default)' if g.is_default else ''}"
            for g in rt.gpus
            if g.is_allowed
        )
        active = "active" if rt.is_active else "inactive"
        print(f"  {rt.framework_type} v{rt.version} [{active}] (id={rt.id}) GPUs: [{gpus}]")


def main():
    parser = argparse.ArgumentParser(
        description="Cloud.ru ML Inference CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list
    p_list = subparsers.add_parser("list", help="List model runs")
    p_list.add_argument("--limit", type=int, help="Max results")
    p_list.add_argument("--offset", type=int, help="Offset for pagination")

    # get
    p_get = subparsers.add_parser("get", help="Get model run details")
    p_get.add_argument("model_run_id", help="Model run UUID")

    # create
    p_create = subparsers.add_parser("create", help="Create a model run")
    p_create.add_argument("--name", required=True, help="Model run name")
    p_create.add_argument(
        "--framework",
        required=True,
        choices=["VLLM", "SGLANG", "OLLAMA", "TRANSFORMERS", "DIFFUSERS", "COMFY"],
        help="Framework type",
    )
    p_create.add_argument(
        "--resource",
        choices=["GPU_A100", "GPU_H100", "GPU_V100", "CPU"],
        help="Resource type",
    )
    p_create.add_argument(
        "--task",
        help="Task type (e.g. TEXT_2_TEXT_GENERATION, EMBEDDING, TEXT_2_IMAGE_GENERATION)",
    )
    p_create.add_argument(
        "--source-type",
        choices=["huggingface", "ollama", "registry", "modelscope"],
        default="huggingface",
        help="Model source type",
    )
    p_create.add_argument("--repo", help="Repository path (e.g. org/model)")
    p_create.add_argument("--model-name", help="Model name within source")
    p_create.add_argument("--revision", help="Model revision/tag")
    p_create.add_argument("--gpu-count", type=int, help="Number of GPUs")
    p_create.add_argument("--gpu-memory", type=int, help="GPU memory in GB")
    p_create.add_argument("--runtime-template-id", help="Runtime template ID")
    p_create.add_argument("--min-scale", type=int, help="Min scale (autoscaling)")
    p_create.add_argument("--max-scale", type=int, help="Max scale (autoscaling)")
    p_create.add_argument(
        "--keep-alive-minutes", type=int, help="Keep alive duration in minutes"
    )

    # update
    p_update = subparsers.add_parser("update", help="Update a model run")
    p_update.add_argument("model_run_id", help="Model run UUID")
    p_update.add_argument("--name", help="New name")
    p_update.add_argument("--min-scale", type=int, help="New min scale")
    p_update.add_argument("--max-scale", type=int, help="New max scale")
    p_update.add_argument("--keep-alive-minutes", type=int, help="Keep alive minutes")

    # delete
    p_del = subparsers.add_parser("delete", help="Delete a model run")
    p_del.add_argument("model_run_id", help="Model run UUID")

    # suspend
    p_sus = subparsers.add_parser("suspend", help="Suspend a model run")
    p_sus.add_argument("model_run_id", help="Model run UUID")

    # resume
    p_res = subparsers.add_parser("resume", help="Resume a model run")
    p_res.add_argument("model_run_id", help="Model run UUID")

    # call
    p_call = subparsers.add_parser("call", help="Call model inference (chat)")
    p_call.add_argument("model_run_id", help="Model run UUID")
    p_call.add_argument("--prompt", required=True, help="User message")
    p_call.add_argument("--system", help="System message")
    p_call.add_argument("--model-name", help="Model name for the request")
    p_call.add_argument(
        "--framework", choices=["VLLM", "SGLANG", "OLLAMA"], help="Framework hint"
    )
    p_call.add_argument("--temperature", type=float, default=0.7)
    p_call.add_argument("--top-p", type=float, default=0.9)
    p_call.add_argument("--with-auth", action="store_true", help="Use IAM auth for call")

    # embed
    p_embed = subparsers.add_parser("embed", help="Call embedding endpoint")
    p_embed.add_argument("model_run_id", help="Model run UUID")
    p_embed.add_argument("--texts", nargs="+", required=True, help="Texts to embed")
    p_embed.add_argument("--model-name", help="Model name")
    p_embed.add_argument("--with-auth", action="store_true")

    # rerank
    p_rerank = subparsers.add_parser("rerank", help="Call rerank endpoint")
    p_rerank.add_argument("model_run_id", help="Model run UUID")
    p_rerank.add_argument("--query", required=True, help="Query string")
    p_rerank.add_argument("--documents", nargs="+", required=True, help="Documents")
    p_rerank.add_argument("--model-name", help="Model name")
    p_rerank.add_argument("--with-auth", action="store_true")

    # ping
    p_ping = subparsers.add_parser("ping", help="Health check a model run")
    p_ping.add_argument("model_run_id", help="Model run UUID")
    p_ping.add_argument("--with-auth", action="store_true")

    # history
    p_hist = subparsers.add_parser("history", help="Get model run event history")
    p_hist.add_argument("model_run_id", help="Model run UUID")

    # quotas
    subparsers.add_parser("quotas", help="Show project quota usage")

    # frameworks
    subparsers.add_parser("frameworks", help="List available frameworks/runtimes")

    args = parser.parse_args()

    commands = {
        "list": cmd_list,
        "get": cmd_get,
        "create": cmd_create,
        "update": cmd_update,
        "delete": cmd_delete,
        "suspend": cmd_suspend,
        "resume": cmd_resume,
        "call": cmd_call,
        "embed": cmd_embed,
        "rerank": cmd_rerank,
        "ping": cmd_ping,
        "history": cmd_history,
        "quotas": cmd_quotas,
        "frameworks": cmd_frameworks,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
